### ISSUE TITLE
Arbitrary Overwrite: DWORD -> QWORD

### ISSUE THREAD

**Issue by GradiusX** [hacksysteam/HackSysExtremeVulnerableDriver#19]
The Write-What-Where vulnerability only allows you to write a DWORD, even in 64-bit.

Would be nice to have both options in 64-bit:
1) DWORD -> Partial Arbitrary Overwrite (this is already there)
2) QWORD -> Full Arbitrary Overwrite

**Comment by hacksysteam** [comment]
@GradiusX True, I will implement it soon as I get some time

**Comment by hacksysteam** [comment]
@GradiusX I was looking into this and I think the Arbitrary Overwrite already does QWORD write on x64 as it uses PULONG_PTR. Can you check again?
