### ISSUE TITLE
Add Arbitrary READ vulnerability

### ISSUE THREAD

**Issue by theevilbit** [hacksysteam/HackSysExtremeVulnerableDriver#24]
It would be cool to have an arbitrary read vulnerability as well.

**Comment by hacksysteam** [comment]
I have commited Relative Out of Bound Read vulnerability. [https://github.com/hacksysteam/HackSysExtremeVulnerableDriver/blob/master/Driver/MemoryDisclosure.c](https://github.com/hacksysteam/HackSysExtremeVulnerableDriver/blob/master/Driver/MemoryDisclosure.c)

I'm also working on adding `Arbitrary Read Write` Vulnerability.

**Comment by hacksysteam** [comment]
@theevilbit look closely in Arbitrary Write vulnerability.

**Comment by hacksysteam** [comment]
@theevilbit Arbitrary Read is already present in HEVD.

Can I close this issue?

**Comment by theevilbit** [comment]
yes, thanks
