### ISSUE TITLE
Load problem Hevd.sys on OSRLOADER (v3.00)

### ISSUE THREAD

**Issue by yavuzwb** [hacksysteam/HackSysExtremeVulnerableDriver#32]
Hello,

When I tried to load HEVD.sys(v3.00) on OSRLOADER, it doesn't work. But I also tried HEVD v1.2 and v2.0 then it works.

Do you have a any idea why?

**"Note: I am working on Windows7x86"**

**Comment by hacksysteam** [comment]
@yavuzwb can you give me any error message to help debug this issue?

**Comment by yavuzwb** [comment]
@hacksysteam Actually, there is no any error message. I am trying to see on the Windbg(debugger machine) but it doesn't come.  I checked also active services on OSRLoader, HEVD was running.
 
After this kind of problem, I tried previous releases, it works without any problem.

**Comment by hacksysteam** [comment]
Oh! I understood the issue. Before loading the driver, can you attach kernel driver and type this commands

```
ed nt!Kd_DEFAULT Mask 8
ed nt!Kd_IHVDRIVER_Mask 8
g
```

After that load the driver and you should see the messages from HEVD.

**Comment by yavuzwb** [comment]
Issue is solved. 

Thank you.

**Comment by sophieboyle** [comment]
Tried the above with HEVD 3.0 on a win7 x86 vm, but sadly it didn't work. OSR Loader has no problem loading the driver and reports success (checked by running querydriver from cmdline), but HEVD header is not seen on DebugView or WinDbg. Had to just use HEVD 2.0 instead

**Comment by hacksysteam** [comment]
Hi @sophieboyle

Can you check on Windows 10 with the above commands. One issue I can think of because of which you don't see the header is because the driver got loaded before you ran those commands.

**Comment by TamatahYT** [comment]
The same issue for Windows 10 x64 tried to load HEVD.sys(v3.00) and v2.00 on OSRLOADER, it doesn't work. 
This driver has been blocked from loading and the commands didn't help

**Comment by TamatahYT** [comment]
C:\lab\HEVD\HEVD.3.00\driver\vulnerable\x64>devcon.exe install .\HEVD.inf Root\HEVD
Device node created. Install is complete when drivers are installed...
Updating drivers for Root\HEVD from C:\lab\HEVD\HEVD.3.00\driver\vulnerable\x64\HEVD.inf.
Drivers installed successfully.

A different solution I used and it worked :

for .inf file:

Removed CatalogFile = HEVD.cat (unsigned driver).

Changed ServiceBinary to %12%\HEVD.sys (C:\Windows\System32\drivers).

Added [Manufacturer] and [HackSys.NTamd64] sections to explicitly tie Root\HEVD to the driver.

Set DefaultDestDir = 12 for the correct driver directory.
-----------------------------------------------------------------------------------------------------
[Version]
Signature   = "$WINDOWS NT$"
Class       = System
ClassGuid   = {4d36e97d-e325-11ce-bfc1-08002be10318}
Provider    = %ManufacturerName%
DriverVer   = 07/02/2019,3.0.0.0

[DestinationDirs]
DefaultDestDir = 12           ; %SystemRoot%\System32\drivers

[SourceDisksNames]
1 = %DiskName%,,,""

[SourceDisksFiles]
HEVD.sys = 1,,

[Manufacturer]
%ManufacturerName%=HackSys,NTamd64

[HackSys.NTamd64]
%DeviceName%=HEVD_Install,Root\HEVD

[HEVD_Install]
CopyFiles = HEVD.DriverFiles

[HEVD.DriverFiles]
HEVD.sys,,,0x00000004        ; COPYFLG_NOVERSIONCHECK

[HEVD_Install.Services]
AddService = %ServiceName%,2,HEVD.ServiceInstall

[HEVD.ServiceInstall]
DisplayName   = %ServiceName%
Description   = %ServiceDesc%
ServiceBinary = %12%\HEVD.sys
ServiceType   = 1              ; SERVICE_KERNEL_DRIVER
StartType     = 3              ; SERVICE_DEMAND_START
ErrorControl  = 1              ; SERVICE_ERROR_NORMAL

[Strings]
ManufacturerName = "HackSys Team"
DiskName         = "HEVD Installation Disk"
ServiceName      = "HEVD"
ServiceDesc      = "HackSys Extreme Vulnerable Driver Service"
DeviceName       = "HackSys Extreme Vulnerable Driver"

**Comment by hacksysteam** [comment]
Hi @TamatahYT are you trying in Test Signing Mode?
