### ISSUE TITLE
Memory access error in HackSysExtremeVulnerableDriver.c

### ISSUE THREAD

**Issue by yavuzwb** [hacksysteam/HackSysExtremeVulnerableDriver#34]
Hello,

I was trying to something that's why I was going to see DriverEntry function. 
I used **"x HEVD!DriverEntry"** command on WinDBG. I got some error about memory access.

I am not sure it's kind of error or my mistake. 
  
<img width="1149" alt="Screen Shot 2019-10-21 at 20 20 07" src="https://user-images.githubusercontent.com/6156480/67227593-34a7b080-f440-11e9-8c8e-644389d04fa4.png">

**Comment by hacksysteam** [comment]
DriverEntry is declared as `#pragma alloc_text(INIT, DriverEntry)`

Excerpt from MSDN:

`A DriverEntry routine can be pageable and should be in an INIT segment so it will be discarded.`

You are seeing this error because of this reason.

**Comment by hacksysteam** [comment]
@yavuzwb Is it okay to close the issue now?

**Comment by hacksysteam** [comment]
@yavuzwb closing the issue. Please re-open it if needed. Thanks
